//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""RedPlayerMovement"",
            ""id"": ""69a24f68-b7b8-441e-b6bf-327708008e56"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9825190f-834a-4902-befc-dddb002e798f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ce204116-7dce-419d-b32f-ee4db1654732"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""606a6677-e511-4802-b62b-ea0b7df226a9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cae8cff4-63df-421c-9255-d46944294645"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""BluePlayerMovement"",
            ""id"": ""b0a07f68-3279-44ac-a313-6c3df9662243"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""741fd93a-fffd-43f1-9dbe-ab3cbf7e2eb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ff0a0972-9306-4bc0-a787-674c51828f86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99f7feb4-4d1e-4b6f-9966-08c9b9a3a512"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61103d77-2dd5-4167-9d2c-88e47606e092"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2646febd-5872-4698-84c4-2c58e2f1d861"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""43343a67-0c66-4ee2-8462-e43992650cb3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6b9b2734-8ae2-4444-888d-f9fad4b7831e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RedPlayerMovement
        m_RedPlayerMovement = asset.FindActionMap("RedPlayerMovement", throwIfNotFound: true);
        m_RedPlayerMovement_Move = m_RedPlayerMovement.FindAction("Move", throwIfNotFound: true);
        // BluePlayerMovement
        m_BluePlayerMovement = asset.FindActionMap("BluePlayerMovement", throwIfNotFound: true);
        m_BluePlayerMovement_Newaction = m_BluePlayerMovement.FindAction("New action", throwIfNotFound: true);
        m_BluePlayerMovement_Move = m_BluePlayerMovement.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RedPlayerMovement
    private readonly InputActionMap m_RedPlayerMovement;
    private List<IRedPlayerMovementActions> m_RedPlayerMovementActionsCallbackInterfaces = new List<IRedPlayerMovementActions>();
    private readonly InputAction m_RedPlayerMovement_Move;
    public struct RedPlayerMovementActions
    {
        private @PlayerInput m_Wrapper;
        public RedPlayerMovementActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_RedPlayerMovement_Move;
        public InputActionMap Get() { return m_Wrapper.m_RedPlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RedPlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IRedPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_RedPlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RedPlayerMovementActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IRedPlayerMovementActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IRedPlayerMovementActions instance)
        {
            if (m_Wrapper.m_RedPlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRedPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_RedPlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RedPlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RedPlayerMovementActions @RedPlayerMovement => new RedPlayerMovementActions(this);

    // BluePlayerMovement
    private readonly InputActionMap m_BluePlayerMovement;
    private List<IBluePlayerMovementActions> m_BluePlayerMovementActionsCallbackInterfaces = new List<IBluePlayerMovementActions>();
    private readonly InputAction m_BluePlayerMovement_Newaction;
    private readonly InputAction m_BluePlayerMovement_Move;
    public struct BluePlayerMovementActions
    {
        private @PlayerInput m_Wrapper;
        public BluePlayerMovementActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_BluePlayerMovement_Newaction;
        public InputAction @Move => m_Wrapper.m_BluePlayerMovement_Move;
        public InputActionMap Get() { return m_Wrapper.m_BluePlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BluePlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IBluePlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_BluePlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BluePlayerMovementActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IBluePlayerMovementActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IBluePlayerMovementActions instance)
        {
            if (m_Wrapper.m_BluePlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBluePlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_BluePlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BluePlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BluePlayerMovementActions @BluePlayerMovement => new BluePlayerMovementActions(this);
    public interface IRedPlayerMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IBluePlayerMovementActions
    {
        void OnNewaction(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
